### ISSUE TITLE
--pattern runs all tests in a suite

### ISSUE THREAD

**Issue by cnx-tcsikos** [morganstanley/testplan#674]
Using the `--pattern <Multitest Name>:<Suite Name>:<Testcase name>` syntax the whole suite runs, instead of a single test.
This change is somewhat recent my previous testplan version (2021-04-15  16:40:03) worked correctly.

```
py test_plan.py --pattern TestCancel:SleepSuite:test_before_sleep_passed
Testplan runpath: C:\...\testplan-cancellation
      [test_before_sleep_passed] -> Passed
      [test_before_sleep_passed2] -> Passed
      [test_sleep] -> Passed
    [SleepSuite] -> Passed
  [TestCancel] -> Passed
[Testplan cancellation] -> Passed
```

**Comment by kn-ms** [comment]
Hi, I think that is by design. It is because your Multitest has strict_order=True.

The strict order is somewhat means that the cases are depending on the state the previous testcase left the environment. In normal run this has no added value as without shuffling these cases are running in order normally. But in interactive mode this also prevents to rerun a previously executed testcase, as the environment state might not be what is expected.

https://testplan.readthedocs.io/en/latest/multitest.html#strict-order

In case of filtering, we either run all the testcases or none in a strictly ordered suite. I guess this is to be in the safe side now. I guess this can be enhanced to find the minimal set of cases that need to be run to reach to the last testcase in the suite that is selected by the filter, but that might be similarly confusing.

**Comment by cnx-tcsikos** [comment]
That explains it, thanks!
